# Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
np_zeroes = np.zeros((2,3)) # 2 rows, 3 columns
print(np_zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
np_random = np.random.rand(2,2)
print(np_random)

[[0.28692772 0.88578047]
 [0.53074306 0.29879265]]


In [6]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
print(a.ndim)

2


In [8]:
print(a.shape)

(2, 3)


In [9]:
b = np.array([1,2,3])
print(b)
print(b.ndim)
print(b.shape)

[1 2 3]
1
(3,)


In [10]:
a.dtype

dtype('int64')

In [11]:
a.size

6

In [12]:
a.itemsize

8

In [13]:
a.size * a.itemsize

48

In [14]:
a.nbytes

48

In [15]:
a = np.array([[x for x in range(1,8)], [x for x in range(8,15)]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
a.shape

(2, 7)

In [17]:
a[1,5]

np.int64(13)

In [18]:
print(a[1,5])

13


In [19]:
a[1,-4]

np.int64(11)

In [20]:
# Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
# How to get a specific column
a[:,3]

array([ 4, 11])

In [22]:
a[0,1:6:2]

array([2, 4, 6])

In [23]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
a[:,2] = 18
print(a)

[[ 1  2 18  4  5  6  7]
 [ 8  9 18 11 12 20 14]]


In [25]:
a[:,5] = [20,21]
print(a)

[[ 1  2 18  4  5 20  7]
 [ 8  9 18 11 12 21 14]]


In [26]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)
print(b.ndim)
print(b.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [27]:
b[0,1,2]

np.int64(6)

In [28]:
b[0,1,:]

array([4, 5, 6])

In [29]:
b[0,:,0]

array([1, 4])

In [30]:
b[:,1,1]

array([ 5, 11])

In [32]:
c = np.zeros((2,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
d = np.ones((3,2,4))
print(d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [35]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [36]:
np.random.rand(3,4)

array([[0.47275471, 0.53842964, 0.0711206 , 0.42639611],
       [0.61158767, 0.59016416, 0.34273237, 0.18025911],
       [0.64294447, 0.16150101, 0.05742143, 0.17438723]])